---
kind: Namespace
apiVersion: v1
metadata:
  name: odoo
  labels:
    name: odoo
---
apiVersion: v1
kind: Service
metadata:
  name: odoo-db
  namespace: odoo
  labels:
    app: odoo-svr
spec:
  ports:
    - port: 5432
  selector:
    app: odoo-svr
    tier: backend
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-db
  namespace: odoo
  labels:
    app: odoo-svr
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: odoo-svr
      tier: backend
  template:
    metadata:
      labels:
        app: odoo-svr
        tier: backend
    spec:
      containers:
      - image: postgres:9.5
        name: odoo-db
        env:
        - name: POSTGRES_USER
          value: odoo
        - name: POSTGRES_PASSWORD
          value: odoo
        - name: PGDATA
          value: /var/lib/postgresql/data/v1
        ports:
        - containerPort: 5432
          name: odoo-db
        volumeMounts:
        - name: odoo-db-pvc
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: odoo-db-pvc
        persistentVolumeClaim:
          claimName: odoo-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: odoo-svr
  namespace: odoo
  labels:
    app: odoo-svr
spec:
  ports:
    - port: 8069
  selector:
    app: odoo-svr
    tier: frontend
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-svr
  namespace: odoo
  labels:
    app: odoo-svr
spec:
  selector:
    matchLabels:
      app: odoo-svr
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: odoo-svr
        tier: frontend
    spec:
      containers:
        - image: levislibra/odoo-librasoft:9.0
          name: odoo
          env:
          # - name: HOST
          #   value: "10.244.1.65"
          # - name: USER
          #   value: odoo
          # - name: PASSWORD
          #   value: odoo
          - name: PGUSER
            value: odoo
          - name: PGPASSWORD
            value: odoo
          - name: PGHOST
            value: odoo-db
          - name: PGPORT
            value: "5432"
          securityContext:
            privileged: true
            runAsUser: 0
          ports:
            - containerPort: 8069
              name: odoo
          volumeMounts:
          - name: odoo-pvc
            mountPath: /var/lib/odoo
      volumes:
      - name: odoo-pvc
        persistentVolumeClaim:
          claimName: odoo-pvc
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv0001
#   labels:
#     type: local
# spec:
#   accessModes:
#     - ReadWriteOnce
#   capacity:
#     storage: 5Gi
#   hostPath:
#     path: /data/pv0001/
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv0002
#   labels:
#     type: local
# spec:
#   accessModes:
#     - ReadWriteOnce
#   capacity:
#     storage: 5Gi
#   hostPath:
#     path: /data/pv0002/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-pvc
  namespace: odoo
  labels:
    app: odoo-svr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-db-pvc
  namespace: odoo
  labels:
    app: odoo-svr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi