---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-db-pvc
  namespace: odoo
  labels:
    app: odoo-svr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi