---
apiVersion: v1
kind: Service
metadata:
  name: odoo-svr
  namespace: odoo
  labels:
    app: odoo-svr
spec:
  ports:
    - port: 8069
      targetPort: 8069
  selector:
    app: odoo-svr
    tier: frontend
  type: NodePort