apiVersion: v1
kind: Service
metadata:
  name: odoo-lb
  namespace: odoo
spec:
  type: LoadBalancer
  selector:
    app: odoo-svr
    tier: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8069
    name: http
