---
apiVersion: v1
kind: Service
metadata:
  name: odoo-svr-longpolling
  namespace: odoo
  labels:
    app: odoo-svr
    tier: frontend
spec:
  ports:
    - port: 8072
      targetPort: 8072
  selector:
    app: odoo-svr
    tier: frontend
  type: NodePort